name: Sauvegarde d'un fichier sur le réseau IPFS
on: push
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          jar cvf EmileALBERICI.war *
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: |
          apk add go-ipfs
          ipfs init
          ipfs daemon &
        shell: alpine.sh --root {0}
      - name: Sauvegarde fichier war sur IPFS
        run: |
          ls -la 
          ipfs swarm peers
          ipfs add EmileALBERICI.war
      - name: Save CID to a Text File
        run: |
          CID=$(ipfs add -q EmileALBERICI.war)
          echo "$CID" > cid.txt

        shell: alpine.sh --root {0}
